apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

android {
    compileSdk 34
    testOptions.unitTests.includeAndroidResources = true

    namespace 'com.ultimatelogger.android.example'
    defaultConfig {
        applicationId "com.ultimatelogger.android.example"
        minSdk 19
        targetSdk 34
        testInstrumentationRunner "${applicationId}.runner.RxAndroidJUnitRunner"
        versionCode 1000
        // Major -> Millions, Minor -> Thousands, Bugfix -> Hundreds. E.g 1.3.72 == 1,003,072
        versionName '0.1.0'

        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        def commonTestDir = 'src/commonTest/java'
        test {
            java.srcDir commonTestDir
        }
        androidTest {
            java.srcDir commonTestDir
        }
    }

    lint {
        checkAllWarnings true
        warningsAsErrors true
        abortOnError false
        lintConfig file("$projectDir/lint.xml")
    }

    packaging {
        resources {
            excludes += [
                'META-INF/services/javax.annotation.processing.Processor',
                'LICENSE.txt',
                'META-INF/license/LICENSE.base64.txt',
                'META-INF/NOTICE.txt',
                'META-INF/LICENSE.txt',
                'META-INF/rxjava.properties',
                'META-INF/MANIFEST.MF'
            ]
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    testOptions {
        unitTests {
            returnDefaultValues = true
        }
    }

    buildFeatures {
        dataBinding = true
    }

}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'org.jetbrains.kotlin' && requested.name == 'kotlin-reflect') {
            details.useVersion kotlin_version
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(path: ':androidloggeroutput')

    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation "androidx.constraintlayout:constraintlayout:2.0.0-alpha2"

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}

// Log out test results to console
tasks.matching { it instanceof Test }.all {
    testLogging.events = ["failed", "passed", "skipped"]
}