apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdk 34

    namespace 'com.ultimatelogger.android.output'
    defaultConfig {
        minSdk 8
        targetSdk 34
        versionCode 1
        versionName "1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    api project(path: ':ultimate-logger-mp')

    testImplementation 'junit:junit:4.13'
    testImplementation 'org.mockito:mockito-core:5.22.0'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:5.4.0'
}