name: Clean+Build+Test

on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: git clone https://arturborowy@github.com/arturborowy/ultimate-logger-mp.git
      - name: Clean+Build+Test
        run: bash ./gradlew clean assembleDebug testDebug