name: Build+Test

on: [ pull_request ]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: clone mp module
        run: git clone https://arturborowy@github.com/arturborowy/ultimate-logger-mp.git

      - name: assemble
        run: bash ./gradlew assemble

      - name: test
        run: bash ./gradlew test